[package]
name = "mpv-sponsorblock"
version = "1.1.0"
edition = "2021"
authors = ["Kevin Gavrois <kevin@gavrois.fr>"]
description = "MPV plugin that allow you to skip sponsors while watching YouTube videos"
repository = "https://github.com/TheCactusVert/mpv-sponsorblock"
keywords = ["mpv", "libmpv", "sponsorblock"]

[lib]
name = "mpv_sponsorblock"
crate-type = ["cdylib"]      # Creates dynamic lib

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
cached = "0.39.0"
curl = "0.4.44"
dirs = "4.0.0"
env_logger = "0.9.1"
hex = "0.4.3"
log = "0.4.17"
mpv-client = "0.3.1"
regex = "1.6.0"
serde = "1.0.145"
serde_derive = "1.0.145"
serde_json = "1.0.86"
sha2 = "0.10.6"
toml = "0.5.9"

[profile.release]
strip = true  # Automatically strip symbols from the binary.
codegen-units = 1
panic = "abort"

